// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bellusBibliotheca2.Models.DataLayer;

#nullable disable

namespace bellusBibliotheca2.Migrations
{
    [DbContext(typeof(BellusContext))]
    partial class BellusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bellusBibliotheca2.Models.SkincareItem", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Serial"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Serial");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Serial = 542977,
                            Brand = "avant",
                            Category = "face cleanser",
                            ExpirationDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "blue volcanic stone purifying and antioxidising cleansing gel",
                            Price = 110m
                        });
                });

            modelBuilder.Entity("bellusBibliotheca2.Models.StylingTool", b =>
                {
                    b.Property<int>("prodSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prodSerial"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkincareItemSerial")
                        .HasColumnType("int");

                    b.Property<int?>("StylingToolprodSerial")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("prodSerial");

                    b.HasIndex("SkincareItemSerial");

                    b.HasIndex("StylingToolprodSerial");

                    b.ToTable("StylingTool");
                });

            modelBuilder.Entity("bellusBibliotheca2.Models.StylingTool", b =>
                {
                    b.HasOne("bellusBibliotheca2.Models.SkincareItem", null)
                        .WithMany("StylingTools")
                        .HasForeignKey("SkincareItemSerial");

                    b.HasOne("bellusBibliotheca2.Models.StylingTool", null)
                        .WithMany("Item")
                        .HasForeignKey("StylingToolprodSerial");
                });

            modelBuilder.Entity("bellusBibliotheca2.Models.SkincareItem", b =>
                {
                    b.Navigation("StylingTools");
                });

            modelBuilder.Entity("bellusBibliotheca2.Models.StylingTool", b =>
                {
                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
